In [1]:
import torch

In [2]:
x = torch.empty(2)
print(x)

tensor([-3.7692e-32,  3.0805e-41])


In [3]:
x = torch.empty(2, 4)
print(x)

tensor([[-3.7693e-32,  3.0805e-41,  5.0447e-44,  0.0000e+00],
        [        nan,  0.0000e+00,  1.3788e-14,  3.6423e-06]])


In [4]:
x = torch.empty(2, 4, 3)
print(x)

tensor([[[-3.7760e-32,  3.0805e-41,  7.0065e-44],
         [ 7.0065e-44,  6.3058e-44,  6.7262e-44],
         [ 6.8664e-44,  6.3058e-44,  6.8664e-44],
         [ 6.8664e-44,  1.1771e-43,  6.8664e-44]],

        [[ 7.9874e-44,  8.1275e-44,  7.1466e-44],
         [ 7.7071e-44,  8.1275e-44,  6.7262e-44],
         [ 7.7071e-44,  6.4460e-44,  7.5670e-44],
         [ 7.1466e-44,  7.4269e-44,  7.9874e-44]]])


In [5]:
# random
x = torch.rand(2, 2)
print(x)

tensor([[0.7085, 0.6286],
        [0.2756, 0.0064]])


In [6]:
# zeros
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [7]:
x = torch.ones(2, 2)
print(x.dtype)

torch.float32


In [8]:
x = torch.ones(2, 2, dtype=torch.int)
print(x.dtype)

torch.int32


In [9]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [10]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x)
print(y)

z = x + y # element wise addition
print(z)

z = torch.add(x, y)
print(z)

tensor([[0.7064, 0.7747],
        [0.9449, 0.9578]])
tensor([[0.4010, 0.9740],
        [0.2635, 0.6247]])
tensor([[1.1074, 1.7487],
        [1.2085, 1.5825]])
tensor([[1.1074, 1.7487],
        [1.2085, 1.5825]])


In [11]:
# inplace addition
y.add_(x)
print(y)

# same for sub/mul/div

tensor([[1.1074, 1.7487],
        [1.2085, 1.5825]])


In [12]:
# slicing

x = torch.rand(5, 3)
print(x.shape)

print(x[:, 0].shape) # 1st column
print(x[1, :].shape) # 2nd row

torch.Size([5, 3])
torch.Size([5])
torch.Size([3])


In [13]:
# value
print(x[1, 1].item())

0.24426472187042236


In [14]:
# reshaping a tensor
x = torch.rand(4, 4)
y = x.view(16)
print(y)
z = x.view(-1, 8)
print(z)

tensor([0.5699, 0.1600, 0.7155, 0.2496, 0.2835, 0.6301, 0.4589, 0.7017, 0.5896,
        0.4155, 0.7050, 0.2397, 0.3930, 0.8195, 0.7618, 0.2925])
tensor([[0.5699, 0.1600, 0.7155, 0.2496, 0.2835, 0.6301, 0.4589, 0.7017],
        [0.5896, 0.4155, 0.7050, 0.2397, 0.3930, 0.8195, 0.7618, 0.2925]])


In [15]:
# numpy <==> torch tensors

import numpy as np

a = torch.ones(5)
print(type(a))

b = a.numpy()
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [16]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [17]:
print(b) # => they both point to the same memory location

[2. 2. 2. 2. 2.]


In [18]:
a = np.ones(5)
print(type(a))

b = torch.from_numpy(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [19]:
a += 1
print(a)

print(b) # => they both point to the same memory location

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [22]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)

    y = y.to(device)

    z = x + y
    print(z)
    # z.numpy() -- error !!

    z = z.to("cpu")
    print(z)

tensor([2., 2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2., 2.])


In [23]:
x = torch.ones(5, requires_grad=True) # tells that we would require to calculate
# the gradient
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
