In [1]:
import torch

In [8]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.9317,  0.0797, -0.8451], requires_grad=True)


In [9]:
y = x+2
print(y)

tensor([1.0683, 2.0797, 1.1549], grad_fn=<AddBackward0>)


In [10]:
z = y*y*2
print(z)

tensor([2.2824, 8.6499, 2.6677], grad_fn=<MulBackward0>)


In [11]:
z = z.mean()
print(z)

tensor(4.5334, grad_fn=<MeanBackward0>)


In [12]:
z.backward() # dz/dx
# Note: we aren't passing any arguments in the backward function
# as it is a scalar value
print(x.grad)

tensor([1.4244, 2.7729, 1.5399])


In [14]:
x = torch.ones(3, requires_grad=True)
y = x+2
z = y*y*2
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([ 1.2000, 12.0000,  0.0120])


In [19]:
x = torch.tensor([0, 1, 2], dtype=torch.float, requires_grad=True)
y = x*x
v = torch.tensor([0, 0.8, 0.2], dtype=torch.float32)
y.backward(v)
print(x.grad)

tensor([0.0000, 1.6000, 0.8000])


## How to avoid PyTorch from keeping history of grad

In [20]:
x = torch.tensor([0, 1, 2], dtype=torch.float, requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)

tensor([0., 1., 2.], requires_grad=True)
tensor([0., 1., 2.])


In [21]:
x = torch.tensor([0, 1, 2], dtype=torch.float, requires_grad=True)
print(x)
y = x.detach()
print(y)

tensor([0., 1., 2.], requires_grad=True)
tensor([0., 1., 2.])


In [22]:
x = torch.tensor([0, 1, 2], dtype=torch.float, requires_grad=True)
print(x)
with torch.no_grad():
    print(x)
    y = x * 2
    print(y)

tensor([0., 1., 2.], requires_grad=True)
tensor([0., 1., 2.], requires_grad=True)
tensor([0., 2., 4.])
