## Concatenate Vs Stack

- **Concatenating** joins a sequence of tensors along an existing axis
- **Stacking** joins a sequence of tensors along a new axis.

In [1]:
import torch

In [2]:
t1 = torch.tensor([1, 1, 1])

In [3]:
# adding an axis
t1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [4]:
t1.unsqueeze(dim=1)

tensor([[1],
        [1],
        [1]])

In [5]:
print(t1.shape)
print(t1.unsqueeze(dim=0).shape)
print(t1.unsqueeze(dim=1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


## In PyTorch

In [6]:
t1 = torch.tensor([1, 1, 1])
t2 = torch.tensor([2, 2, 2])
t3 = torch.tensor([3, 3, 3])

In [7]:
torch.cat(
    (t1, t2, t3),
    dim = 0
)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [8]:
torch.stack(
    (t1, t2, t3),
    dim = 0 # creating a new axis at dim=0, and stacking along it
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [9]:
torch.cat(
    (t1.unsqueeze(0),
     t2.unsqueeze(0),
     t3.unsqueeze(0)
     ),
    dim = 0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [10]:
torch.stack(
    (t1, t2, t3),
    dim = 1 # creating a new axis at dim=1, and stacking along it
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [11]:
torch.cat(
    (t1.unsqueeze(1),
     t2.unsqueeze(1),
     t3.unsqueeze(1)
     ),
    dim = 1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])