In [1]:
import torch
import numpy as np

<br>

## Tensor class

<br>

In [2]:
t = torch.Tensor()
type(t)

torch.Tensor

<br>

## Tensor Attributes

<br>

In [3]:
print(t.dtype) # type of data
print(t.device) # device of tensor
print(t.layout)

torch.float32
cpu
torch.strided


In [4]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

<br>

Tensor computations between tensors depend on the device.

<br>

In [5]:
# They don't depend on the type
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([1., 2., 3.])

In [7]:
t1.dtype

torch.int64

In [8]:
t2.dtype

torch.float32

In [9]:
t1 + t2

tensor([2., 4., 6.])

In [12]:
# But they do depend on the device
t1 = torch.tensor([1, 2, 3])
t2 = t1.cuda()

In [13]:
t1.device

device(type='cpu')

In [14]:
t2.device

device(type='cuda', index=0)

In [15]:
t1 + t2 # gives error

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

<br>

## Creating Tensors Using Data

<br>

In [16]:
import numpy as np

In [17]:
data = np.array([1, 2, 3])
type(data)

numpy.ndarray

In [18]:
# torch.Tensor --> class constructor
torch.Tensor(data) # converted it to Float

tensor([1., 2., 3.])

In [19]:
torch.tensor(data) # remained Integer

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

<br>

## Creating Options Without Data

<br>

In [22]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [23]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [24]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [25]:
torch.rand(2, 2)

tensor([[0.8206, 0.7716],
        [0.5866, 0.3378]])