In [1]:
import torch
import numpy as np

In [2]:
data = np.array([1, 2, 3])

In [3]:
t1 = torch.Tensor(data) # using the class constructor

t2 = torch.tensor(data) # using a factory function
# factory function is another way to create objects
# instead of using class constructors.
# It allows more dynamic object creation.

t3 = torch.as_tensor(data) # factory function
t4 = torch.from_numpy(data) # factory function

In [4]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [5]:
print(t1.dtype) # default global dtype of the class constructor
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [6]:
torch.get_default_dtype()

torch.float32

In [7]:
# factory function choose their dtype based on the given data
# This is called type inference

print(torch.tensor(np.array([1, 2, 3])))
print(torch.tensor(np.array([1., 2., 3.])))

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.], dtype=torch.float64)


In [8]:
torch.tensor(np.array([1, 2, 3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

<br>

## Memory: Sharing vs Copying

<br>

In [9]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [10]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data) 
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [11]:
# modifying the data of the numpy array
data[0] = 0
data[1] = 0
data[2] = 0

In [12]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [13]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
