In [1]:
import torch
import numpy as np

In [3]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype = torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype = torch.float32)

In [4]:
# examples:
# 1st axis
print(t1[0])

# 2nd axis
print(t1[0][0])

tensor([1., 2.])
tensor(1.)


In [5]:
# corresponding elements
print(t1[0][0], t2[0][0])

tensor(1.) tensor(9.)


## Element-wise operations

In [6]:
# similarly for -,* and /
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

## Broadcasting

In [7]:
# similarly for -,* and /
print(t1 + 2)
print(t1.add(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[3., 4.],
        [5., 6.]])


In [10]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [11]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape)
    ,dtype=torch.float32
)

# which is same as t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [18]:
t1 = torch.tensor([
    [1,1],
    [1,1],
    [1,1]
], dtype=torch.float32)

t2 = torch.tensor([2, 4], dtype=torch.float32)

In [19]:
t1.shape

torch.Size([3, 2])

In [20]:
t2.shape

torch.Size([2])

In [21]:
t1 + t2

tensor([[3., 5.],
        [3., 5.],
        [3., 5.]])

In [22]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.],
       [2., 4.]], dtype=float32)

In [23]:
t1.numpy() + np.broadcast_to(t2.numpy(), t1.shape)

# same as t1 + t2 in torch/tensors

array([[3., 5.],
       [3., 5.],
       [3., 5.]], dtype=float32)

#### The lower rank tensor t2 will be transformed via broadcasting to match the shape of the higher rank tensor t1, and the element-wise operation will be performed as usual.

In [24]:
t1 + t2

tensor([[3., 5.],
        [3., 5.],
        [3., 5.]])

In [25]:
t1 = torch.tensor([
    [1,2,3]
])

t2 = torch.tensor([
    [1],
    [2],
    [3],
])

In [26]:
t1.shape

torch.Size([1, 3])

In [27]:
t2.shape

torch.Size([3, 1])

In [28]:
t1 + t2

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [29]:
t1 = torch.tensor([
    [1,2,3],
    [1,2,3]
])

t2 = torch.tensor([
    [1],
    [2],
    [3],
])

In [30]:
t1.shape

torch.Size([2, 3])

In [31]:
t2.shape

torch.Size([3, 1])

In [32]:
t1 + t2 # error

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

## Comparision Operations are Element-wise Operations

In [34]:
t = torch.tensor([
    [0,5,0],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

print(t.eq(0)) # equal to 0

print(t.ge(0)) # greater than equal to 0

print(t.gt(0)) # greater than to 0

print(t.lt(0)) # less than to 0

print(t.le(7)) # less than equal to 7

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])
tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])


In [35]:
# How is broadcasting involved in this?

# t.le(7)
t <= torch.tensor(
    np.broadcast_to(7, t.shape)
    ,dtype=torch.float32
)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [36]:
torch.tensor(
    np.broadcast_to(7, t.shape)
    ,dtype=torch.float32
)

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

## Element-Wise Operations Using Functions

In [37]:
print(t.abs())

print(t.sqrt())

print(t.neg())

print(t.neg().abs())

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])
tensor([[0.0000, 2.2361, 0.0000],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])
tensor([[-0., -5., -0.],
        [-6., -0., -7.],
        [-0., -8., -0.]])
tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])
