## ArgMax and Reduction Tensor Operations

In [1]:
import torch
import numpy as np

In [2]:
t = torch.tensor([
    [0, 1, 0],
    [2, 0, 2],
    [0, 3, 0]
], dtype=torch.float32)

In [3]:
t.sum() # summation of all elements

tensor(8.)

In [4]:
t.numel()

9

In [5]:
t.sum().numel()

1

In [6]:
t.sum().numel() < t.numel()

True

In [7]:
t.prod()

tensor(0.)

In [8]:
t.mean()

tensor(0.8889)

In [9]:
t.std()

tensor(1.1667)

In [10]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [11]:
t.shape

torch.Size([3, 4])

In [12]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [13]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [14]:
t.shape

torch.Size([3, 4])

## Argmax

In [31]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [32]:
t.max()

tensor(5.)

In [33]:
t.argmax() # axis isn't specified

tensor(11)

In [34]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [35]:
# with specific axis
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [37]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [36]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [38]:
t.argmax(dim=1)

tensor([3, 1, 3])